const sdk = require("node-appwrite");

const APPWRITE_CLOUD_URL = process.env.APPWRITE_URL; // Fixed to match .env
const APPWRITE_PROJECT_ID = process.env.APPWRITE_PROJECT_ID;
const APPWRITE_API_KEY = process.env.APPWRITE_API_KEY; // Fixed key name to match .env

// All collection IDs
const APPWRITE_REPORTS_COLLECTION_ID = process.env.APPWRITE_REPORTS_COLLECTION_ID
const APPWRITE_BLOCKED_COLLECTION_ID = process.env.APPWRITE_BLOCKED_COLLECTION_ID
const APPWRITE_HOBBIES_COLLECTION_ID = process.env.APPWRITE_HOBBIES_COLLECTION_ID
const APPWRITE_PREFERENCE_COLLECTION_ID = process.env.APPWRITE_PREFERENCE_COLLECTION_ID
const APPWRITE_HAS_SHOWN_COLLECTION_ID = process.env.APPWRITE_HAS_SHOWN_COLLECTION_ID
const APPWRITE_MESSAGES_COLLECTION_ID = process.env.APPWRITE_MESSAGES_COLLECTION_ID
const APPWRITE_NOTIFICATIONS_COLLECTION_ID = process.env.APPWRITE_NOTIFICATIONS_COLLECTION_ID
const APPWRITE_BIODATA_COLLECTION_ID = process.env.APPWRITE_BIODATA_COLLECTION_ID
const APPWRITE_LOCATION_COLLECTION_ID = process.env.APPWRITE_LOCATION_COLLECTION_ID
const APPWRITE_IMAGES_COLLECTION_ID = process.env.APPWRITE_IMAGES_COLLECTION_ID
const APPWRITE_CONNECTIONS_COLLECTION_ID = process.env.APPWRITE_CONNECTIONS_COLLECTION_ID
const APPWRITE_USERS_COLLECTION_ID = process.env.APPWRITE_USERS_COLLECTION_ID

const client = new sdk.Client()
  .setEndpoint(APPWRITE_CLOUD_URL)
  .setProject(APPWRITE_PROJECT_ID)
  .setKey(APPWRITE_API_KEY);

const databases = new sdk.Databases(client);
const account = new sdk.Account(client); // Fixed to use sdk instead of undefined appwrite

// Constants
const DATABASE_ID = process.env.APPWRITE_DATABASE_ID;

module.exports = {
  APPWRITE_CLOUD_URL,
  APPWRITE_PROJECT_ID,
  APPWRITE_API_KEY,
  databases,
  DATABASE_ID,
  account
  ,
  APPWRITE_REPORTS_COLLECTION_ID,
  APPWRITE_BLOCKED_COLLECTION_ID,
  APPWRITE_HOBBIES_COLLECTION_ID,
  APPWRITE_PREFERENCE_COLLECTION_ID,
  APPWRITE_HAS_SHOWN_COLLECTION_ID,
  APPWRITE_MESSAGES_COLLECTION_ID,
  APPWRITE_NOTIFICATIONS_COLLECTION_ID,
  APPWRITE_BIODATA_COLLECTION_ID,
  APPWRITE_LOCATION_COLLECTION_ID,
  APPWRITE_IMAGES_COLLECTION_ID,
  APPWRITE_CONNECTIONS_COLLECTION_ID,
  APPWRITE_USERS_COLLECTION_ID
}